name: build
on: [push]
jobs:
  build-java-maven:
    runs-on: ubuntu-latest
    container: maven:3-openjdk-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn --batch-mode package
      - uses: actions/upload-artifact@v3.1.0
        with:
          path: target/*.jar
